### ISSUE TITLE
声音无法使用

### ISSUE THREAD

**Issue by C-SF-C** [SummerEmber/DELL-XPS13-9360#1]
请问声音如何解决，声卡未驱动起来！

**Comment by SummerEmber** [comment]
是用的我提供的EFI吗？外放应该没问题，AppleALC的方式，layout-id为13(0D000000)，已经在Clover Configurator设备设置-属性中添加好了。耳机插孔需要用/kexts/ComboJack/中的文件进行修复没，具体操作可百度。

**Comment by C-SF-C** [comment]
非常感谢您的EFI，问题出在我这里，不知为什么我的layout-id没有正常加载；多次尝试后，在启动参数重添加layout-id=13解决。希望您能继续跟新EFI

**Comment by C-SF-C** [comment]
非常感谢您的EFI，问题出在我这里，不知为什么我的layout-id没有正常加载；多次尝试后，在启动参数重添加layout-id=13解决。希望您能继续跟新EFI
