### ISSUE TITLE
摄像头问题

### ISSUE THREAD

**Issue by AmourHah** [SummerEmber/DELL-XPS13-9360#2]
FaceTime摄像头开机后第一次打开可以使用，重新打开FaceTime就无法使用了。同时在第一次打开之后如果有切换应用，那么摄像头会直接黑屏。
不知道您有没有遇到这种问题以及如何解决的？

**Comment by SummerEmber** [comment]
暂时没有发现FaceTime摄像头不稳定的问题。建议升级BIOS为最新再尝试一下

**Comment by forestkopa** [comment]
0.62啥时候更新

**Comment by SummerEmber** [comment]
> 0.62啥时候更新

已更新
