### ISSUE TITLE
声卡需要更改LayoutID

### ISSUE THREAD

**Issue by wang3377** [SummerEmber/DELL-XPS13-9360#4]
同XPS13-9360, Realtek256声卡，直接使用这套EFI声卡无法驱动。网上查了下，用hackintool把LayoutID改成56（0X38）后正常。

**Comment by SummerEmber** [comment]
多谢反馈！经测试，我手里的这台9360使用Layoutid=13或56均可，可能是声卡硬件细微差异导致。

**Comment by SummerEmber** [comment]
> 同XPS13-9360, Realtek256声卡，直接使用这套EFI声卡无法驱动。网上查了下，用hackintool把LayoutID改成56（0X38）后正常。

多谢反馈！经测试，我手里的这台9360使用Layoutid=13或56均可，可能是声卡硬件细微差异导致。

**Comment by SummerEmber** [comment]
默认声卡id已设置为56
